a='pooja'
print(a[0])#p
print(a[:])#pooja
print(a[0:-1])#pooj
print(a[0:-2])#poo
print(a[0:6])#pooja
print(a[2:5])#oja
print(a[2:4])#oj
print(a[-1:-5])
a='python'
print(a[::])#python
print(a[::1])#python
print(a[::2])#pto
print(a[::3])#ph
print(a[::4])#po
print(a[::5])#pn
print(a[::6])#p
print(a[::-1])#nohtyp
print(a[::-2])#nhy
print(a[::-3])#nt
print(a[::-4])#ny
print(a[::-5])#np
print(a[::-6])#n
print(a[1:6:])#ython
print(a[2:5:])#tho

